layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-diagrams
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

collections:
  talks:
    output: true

pinned_repos:
  - name: juwit/gitlab-classrooms
    html_url: https://github.com/juwit/gitlab-classrooms
    description: GitLab Classroom is a modest clone of Github Classroom, aimed at GitLab.
    language: Java
  - name: gaia-app/gaia
    html_url: https://github.com/gaia-app/gaia
    description: Gaia is a Terraform 🌍 UI for your modules, and self-service infrastructure 👨‍💻
    language: Java
    stargazers_count: 794
    forks_count: 82
  - name: gaia-app/runner
    html_url: https://github.com/gaia-app/runner
    description:  gaia-runner is the service that runs the Terraform jobs in Gaia. 
    language: Java
    stargazers_count: 2
    forks_count: 11
  - name: juwit/reveal-quiz
    html_url: https://github.com/juwit/reveal-quiz
    description: reveal.js plugin that allows adding quiz as slides.
    language: TypeScript

show_stats: true

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: julien-wittouck
  mastodon: '@codekaio@mas.to'
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: CodeKaio
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/Java
    image_url: /assets/topics/java.png

  - name: Docker
    web_url: https://github.com/topics/Docker
    image_url: /assets/topics/docker.png

  - name: Linux
    web_url: https://github.com/topics/Linux
    image_url: /assets/topics/linux.png

  - name: Kubernetes
    web_url: https://github.com/topics/Kubernetes
    image_url: /assets/topics/kubernetes.png

  - name: Terraform
    web_url: https://github.com/topics/Terraform
    image_url: /assets/topics/terraform.png


jekyll-diagrams:
  graphviz:
    graph_attributes: bgcolor=#fafbfc
